### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by zacharyrkennedy** [zacharyrkennedy/LightCurveGrapher#1]
### Todo List

This is a list of planned features for the light curve graphing software. If you'd like to suggest a feature please comment on this post. If you'd like to report a bug you've found, please make your own "issue" thread.

- [ ] Restructure Code to be cleaner and more useable for updates
- [x] Remake logo in scaleable form **(Completed 6/07/2022)** 
- [x] Implement Logo **(Completed 5/31/2022)**
- [x] Add error messages when a non-supported file type is selected **(Completed 5/31/2022)**
- [x] Add the ability for the software to auto-update **(Completed 6/10/2022)**
- [x] Add a "quick-save" checkbox that saves a graph without plotting it. **(Completed 5/31/2022)**
- [x] Investigate ways to make the program prettier **(Completed 6/07/2022)**
- [ ] Investigate ways to optimize the program
- [ ] Add the ability to apply algorithms to multiple spreadsheets to get a phase-folded graph
- [ ] Add more customization options for the graph settings window
- [ ] Add preset customizations for the graph settings
- [ ] Add the ability to save your own presets
- [x] Only "unlock" the number of radio buttons corresponding to the number of check stars **(Completed 6/09/2022)**
- [x] Allow the graph settings window info to be saved in between graphs **(Completed 7/11/2022)**
- [x] Add tooltips to some buttons and boxes **(Completed 5/31/2022)**
- [ ] Update the README.MD file with new pictures etc
- [ ] Fix the issue where the .exe file is getting falsely flagged as malware by antiviruses
- [ ] Add support for .csv files that aren't in the right format
- [ ] Automatically convert .xslv files to .csv

### Known Bugs found by me
- [x] If you don't go into graph settings at least once before trying to graph, you get an error **(Fixed 6/09/2022)**
- [x] If you select a .csv file the gear icon "unlocks" but then if you select a "bad" file after that, it remains unlocked. It needs to lock when selecting a bad file **(Fixed 6/09/2022)**
